src/components/NavBar.vue
src/main.ts
src/styles/main.postcss

Scroll position was not resetting while navigating between pages. Fixed it by setting scrollBehavior. Then I realized it doesn't work nevertheless. I found its reason on StackOverflow.
Context:
https://stackoverflow.com/a/18573599
https://next.router.vuejs.org/guide/advanced/scroll-behavior.html

fix: scroll restoration

---

pages/index.md

chore: typo

---

src/components/Post.vue

fix: decode url

---

scripts/rss.ts

To make atom feed valid, according to https://validator.w3.org/feed/ (and make it nicer for feed readers :)

Add link to feed

---

src/components/Post.vue

Hi Anthony,
with this PR relative links inside your markdown pages like `/posts/journey-with-icons` will no longer cause a hard redirect. I hope the changes appeal to you.
Also, one single event listener should be more performant (in theory at least).

feat: handle internal links inside md content

---

.gitattributes

More markdown language percentages look more like a blog

feat: md statistics

---

pages/posts/reimagine-atomic-css.md

chore: grammar fix

---

index.html
package.json
scripts/rss.ts
src/App.vue
src/components/AppLink.vue
src/components/ToggleTheme.vue

iPhone safe area color different from background in dark mode.
It looks weird in dark mode.
|before|after|
|:--:|:--:|
|![53042fd6f1c8810e6407f8cd362f2b1](https://user-images.githubusercontent.com/54026110/191280334-b14ef047-180f-4b8c-9429-cf91fc42f6fd.jpg)|![37c92abbc5a79a826228abe7d23508e](https://user-images.githubusercontent.com/54026110/191280371-e7c63102-30b9-4325-9aff-a68143468da9.jpg)|

fix: safe area color different from background in dark mode

---

pages/posts/dev-ssr-on-nuxt.md

blog: update article

---

pages/podcasts.md
pages/posts/index.md
pages/projects.md
pages/streams.md
pages/talks.md

chore: fix eslint error

---

pages/posts/why-not-prettier-zh.md
pages/posts/why-not-prettier.md
src/components/GitHubLink.vue

Hi！👋，很喜欢 《Why I don't use Prettier》，给了我很大的启发。
想要推荐给我的朋友和同事，但是仅有英文版本，但看其他中文博客有人贡献翻译，因此我也试图翻译该博文，希望可以起到作用。

feat: translate why-not-prettier

---

scripts/redirects.ts

use the `html_url` property directly to replace `url`

chore: update

---

pages/posts/composable-vue-vueday-2021.md

Just fixing a typo in a subheading -> https://antfu.me/posts/composable-vue-vueday-2021#ref-undef
None
Thank you so much for this informative article, I have learnt so much from reading it! 💚

chore: fix typo in heading

---

src/styles/markdown.css

I just feel that the code block's font-size of `1.05em` is a little large 😅 .  If you feel ok, you can close this pr.

style: adjust shiki fontSize

---

pages/sponsors-list.md
src/components/ListProjects.vue
src/components/SponsorButton.vue

Add transition effect to **_Sponsor to support my work_** button of https://antfu.me/projects and https://antfu.me/sponsors-list
none
The transition effect are same with the Project item

style: sponsor color transition

---

src/styles/main.css

add selection style
same as nuxt devtools selection style

style: selection

---

src/components/ListProjects.vue

style: `project-grid > item` mouse hover style

---

vite.config.ts

chore: fix typo

---

src/styles/main.css

Opacity cannot be more than 1. Opacity 1 is 10000%.
N/A
N/A

chore: fix opacity value

---

pages/index.md

chore(bio): fix typo

---

pages/index.md

chore: typo fix UnoCSS link

---

pages/posts/isomorphic-dirname.md

docs: fix tsup domain

---

pnpm-workspace.yaml

This PR removed extraneous backslash in `pnpm-workspace.yaml`.

fix: remove extraneous backslash

---

pages/posts/async-sync-in-between.md

Fixed a typo

---

pages/posts/categorize-deps.md

chore: add missing space

---

data/talks.ts

add sneak peek of vite devtools recording

chore: add sneak peek of vite devtools recording
